In [ ]:
##

In [41]:
import numpy as np
n=4
x=np.linspace(1,2,n+1)
h=x[1]-x[0]
#geting A
A=np.zeros((n+1,n+1))
A[0,0]=1
A[n,n]=1
for i in range(1,n):
    A[i,i-1]=16*x[i]
    A[i,i]=1-32*x[i]
    A[i,i+1]=16*x[i]
print("A=",A)
b=np.array([1,0,0,0,2])
print("b=",b)
y=np.linalg.solve(A,b)
print(y)
for j in range(0,4):
    print(f"y({j})={y[j]}")
   

















A= [[  1.   0.   0.   0.   0.]
 [ 20. -39.  20.   0.   0.]
 [  0.  24. -47.  24.   0.]
 [  0.   0.  28. -55.  28.]
 [  0.   0.   0.   0.   1.]]
b= [1 0 0 0 2]
[1.         1.35125604 1.63494928 1.85051963 2.        ]
y(0)=0.9999999999999997
y(1)=1.3512560416537014
y(2)=1.6349492812247182
y(3)=1.8505196340780383
