In [4]:
import numpy as np
h,k=1/3,1/3
x=np.linspace(0,1,4)
y=np.linspace(1,0,4)
u=np.zeros((4,4))

u[-1,:]=2*x
u[:,0]=-y
u[0,:]=2*x-1
u[:,-1]=2-y
for k in range(100):
    for i in range(1,3):
        for j in range(1,3):
            u[i,j]=round(0.25*(u[i-1,j]+u[i,j+1]+u[i+1,j]+u[i,j-1]),6)
print(u)

[[-1.         -0.33333333  0.33333333  1.        ]
 [-0.66666667 -0.          0.666667    1.33333333]
 [-0.33333333  0.333333    1.          1.66666667]
 [-0.          0.66666667  1.33333333  2.        ]]


In [75]:
b=np.zeros((5,6))
b[0:3,1]=2
print(b)

[[0. 2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
